version: '3.8'

services:
  #APP
  app:
    container_name: "${APP_NAME}_app"
    build:
      context: ./
      dockerfile: .docker/Dockerfile
      args:
        PORT: ${APP_PORT}
        ALPINE_VERSION: ${ALPINE_VERSION}
    ports:
    - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
      - .docker/config/nginx.conf:/etc/nginx/nginx.conf
      - .docker/config/fpm-pool.conf:/etc/php7/php-fpm.d/www.conf
      - .docker/config/php.ini:/etc/php7/conf.d/custom.ini
      - .docker/config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf